<?php
$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
/** @var \Zend\Form\Form $album */
$album = $this->form->get('album')->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
/** @var \Zend\Form\Form $artist */
$artist = $this->form->get('album')->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

// This provides CSS classes for the submit button:
/** @var \Zend\Form\Form $submit */
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('album', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($album) ?>
        <?= $this->formElement($album) ?>
        <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($this->form->get('album')->get('id'));
echo $this->form()->closeTag();
