<?php
$title = 'Add new Film';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
    <p>
        <a href="<?= $this->url('film', ['action' => 'add']) ?>">Add new Film</a>
    </p>
<?php
// This provides a default CSS class and placeholder text for the title element:
/** @var \Zend\Form\Form $title */
$title = $this->form->get('film')->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Film titre');

// This provides a default CSS class and placeholder text for the artist element:
/** @var \Zend\Form\Form $synopsis */
$synopsis = $this->form->get('film')->get('synopsis');
$synopsis->setAttribute('class', 'form-control');
$synopsis->setAttribute('placeholder', 'Film synopsis');

// This provides a default CSS class and placeholder text for the artist element:
/** @var \Zend\Form\Form $genre */
$genre = $this->form->get('film')->get('genre');
$genre->setAttribute('class', 'form-control');
$genre->setAttribute('placeholder', 'Film genre');

// This provides a default CSS class and placeholder text for the artist element:
/** @var \Zend\Form\Form $director */
$director = $this->form->get('film')->get('director');
$director->setAttribute('class', 'form-control');
$director->setAttribute('placeholder', 'Film Réalisateur');


// This provides a default CSS class and placeholder text for the artist element:
/** @var \Zend\Form\Form $dateRelease */
$dateRelease = $this->form->get('film')->get('date_release');
$dateRelease->setAttribute('class', 'form-control');
$dateRelease->setAttribute('placeholder', 'Film Réalisateur');

/** @var \Zend\Form\Form $category */
$category = $this->form->get('film')->get('category');
$category->setAttribute('class', 'form-control');
$category->setAttribute('placeholder', 'Film Categories');

// This provides CSS classes for the submit button:
/** @var \Zend\Form\Form $submit */
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('film', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($title) ?>
        <?= $this->formElement($title) ?>
        <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($synopsis) ?>
        <?= $this->formElement($synopsis) ?>
        <?= $this->formElementErrors()->render($synopsis, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($genre) ?>
        <?= $this->formElement($genre) ?>
        <?= $this->formElementErrors()->render($genre, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($director) ?>
        <?= $this->formElement($director) ?>
        <?= $this->formElementErrors()->render($director, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($dateRelease) ?>
        <?= $this->formElement($dateRelease) ?>
        <?= $this->formElementErrors()->render($dateRelease, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($category) ?>
        <?= $this->formElement($category) ?>
        <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($this->form->get('film')->get('id'));
echo $this->form()->closeTag();
